// <auto-generated />
namespace Asn_23.Migrations.GoodSamaritan
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SecondDataMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecondDataMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201502180625035_SecondDataMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
